export const CURRENCY_LIST_FETCH_IS_LOADING = 'CURRENCY_LIST_FETCH_IS_LOADING';
export const CURRENCY_LIST_FETCH_SUCCESS = 'CURRENCY_LIST_FETCH_SUCCESS';
export const ADD_CURRENCY_TO_FAVORITES = 'ADD_CURRENCY_TO_FAVORITES';
export const REMOVE_CURRENCY_FROM_FAVORITES = 'REMOVE_CURRENCY_FROM_FAVORITES';
export const SELECT_CURRENCY_FROM_LIST = 'SELECT_CURRENCY_FROM_LIST';

export const CURRENCY_CHART_DATA_FETCH_IS_LOADING = 'CURRENCY_CHART_DATA_FETCH_IS_LOADING';
export const CURRENCY_CHART_DATA_FETCH_SUCCESS = 'CURRENCY_CHART_DATA_FETCH_SUCCESS';